search_settings:
  num_results: 1
  min_delay: 1
  max_delay: 3
  timeout: 10

criteria:
  credibility:
    - What are the reviews of

  referential:
    - What are the partners of

  compliance:
    - What are the compliance papers of